image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Backend
    init: |
      composer install
      cp .env.example .env
      php artisan key:generate
      php artisan migrate
      php artisan db:seed --class=ProductSeeder
    command: php artisan serve --host=0.0.0.0 --port=8000

  - name: Install Frontend
    init: |
      cd client
      npm install
      npm run build
    command: echo "Client built and ready."

ports:
  - port: 8000
    onOpen: open-preview
